name: S3 Backup

on:
  push:
    branches:
      - master
  #  schedule:
  #   - cron: '0 0 * * *'  # Optional: Schedule the action (daily at midnight)

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run S3 Backup
      uses: peter-evans/s3-backup@v1
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        MIRROR_TARGET: ${{ secrets.MIRROR_TARGET }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      with:
        args: --overwrite --remove
